### ISSUE TITLE
strane righe verticali

### ISSUE THREAD

**Issue by ddavidebor** [fermiumlabs/website#37]
Ridimensionando la pagina about us con il menù aperto si formano strane righe verticali.
Si formano anche aprendo il menù

Dipende dalla larghezza della pagina. Forse dal browswe
![screen shot 2016-12-29 at 04 45 23](https://cloud.githubusercontent.com/assets/9055742/21536326/d18c59fc-cd81-11e6-95c8-6c2349e386ca.png)

**Comment by ddavidebor** [comment]
pronta per essere affrontata da terzisti

**Comment by SimoneTosato** [comment]
Non riproducibile, chiudo momentaneamente
